"""add Stock from field to stocks

Revision ID: ab85bb9e09de
Revises: 468210b6ce3f
Create Date: 2026-02-07 22:31:09.625696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab85bb9e09de'
down_revision: Union[str, Sequence[str], None] = '468210b6ce3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('stockFrom', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='Stock from where'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'stockFrom')
    # ### end Alembic commands ###
