"""fix stock optionals

Revision ID: d176b7a29fe4
Revises: ab85bb9e09de
Create Date: 2026-02-07 22:33:27.662839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d176b7a29fe4"
down_revision: Union[str, Sequence[str], None] = "ab85bb9e09de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stocks", schema=None) as batch_op:
        batch_op.alter_column(
            "stockFrom",
            existing_type=sa.VARCHAR(),
            nullable=True,
            existing_server_default=sa.text("'Stock from where'"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stocks", schema=None) as batch_op:
        batch_op.alter_column(
            "stockFrom",
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("'Stock from where'"),
        )
    # ### end Alembic commands ###
